DEVICE: "0" # "0" means GPU 0, "0,1" means GPU 0 and 1, etc.
EXP_NAME: "rrdbnet_x4-DFO2K" # Name of the experiment
PHASE: "psnr" # psnr, gan
UPSCALE_FACTOR: 4

DEGRADATION_MODEL_PARAMETERS_DICT:
  SINC_KERNEL_SIZE: 21
  GAUSSIAN_KERNEL_RANGE: [ 7, 9, 11, 13, 15, 17, 19, 21 ]
  GAUSSIAN_KERNEL_TYPE: [ "ISOTROPIC", "ANISOTROPIC","GENERALIZED_ISOTROPIC", "GENERALIZED_ANISOTROPIC","PLATEAU_ISOTROPIC", "PLATEAU_ANISOTROPIC" ]
  # first-order degradation parameters
  GAUSSIAN_KERNEL_PROBABILITY1: [ 0.45, 0.25, 0.12, 0.03, 0.12, 0.03 ]
  SINC_KERNEL_PROBABILITY1: 0.1
  GAUSSIAN_SIGMA_RANGE1: [ 0.2, 3 ]
  GENERALIZED_KERNEL_BETA_RANGE1: [ 0.5, 4 ]
  PLATEAU_KERNEL_BETA_RANGE1: [ 1, 2 ]
  # second-order degradation parameters
  GAUSSIAN_KERNEL_PROBABILITY2: [ 0.45, 0.25, 0.12, 0.03, 0.12, 0.03 ]
  SINC_KERNEL_PROBABILITY2: 0.1
  GAUSSIAN_SIGMA_RANGE2: [ 0.2, 1.5 ]
  GENERALIZED_KERNEL_BETA_RANGE2: [ 0.5, 4 ]
  PLATEAU_KERNEL_BETA_RANGE2: [ 1, 2 ]
  SINC_KERNEL_PROBABILITY3: 0.8

DEGRADATION_PROCESS_PARAMETERS_DICT:
  # the probability of triggering a first-order degenerate operation
  FIRST_BLUR_PROBABILITY: 1.0
  # first-order degenerate operating parameters
  RESIZE_PROBABILITY1: [ 0.2, 0.7, 0.1 ]
  RESIZE_RANGE1: [ 0.15, 1.5 ]
  GRAY_NOISE_PROBABILITY1: 0.4
  GAUSSIAN_NOISE_PROBABILITY1: 0.5
  NOISE_RANGE1: [ 1, 30 ]
  POISSON_SCALE_RANGE1: [ 0.05, 3 ]
  JPEG_RANGE1: [ 30, 95 ]
  # the probability of triggering a second-order degenerate operation
  SECOND_BLUR_PROBABILITY: 0.8
  # second-order degenerate operating parameters
  RESIZE_PROBABILITY2: [ 0.3, 0.4, 0.3 ]
  RESIZE_RANGE2: [ 0.3, 1.2 ]
  GRAY_NOISE_PROBABILITY2: 0.4
  GAUSSIAN_NOISE_PROBABILITY2: 0.5
  NOISE_RANGE2: [ 1, 25 ]
  POISSON_SCALE_RANGE2: [ 0.05, 2.5 ]
  JPEG_RANGE2: [ 30, 95 ]

DATASET:
  MODE: "degradation" # degradation, paired
  TRAIN_GT_IMAGES_DIR: "/home/dl/Datasets/DFO2K/sub_image_384x384"
  TRAIN_LR_IMAGES_DIR: ""

  VAL_GT_IMAGES_DIR: "/home/dl/Datasets/Set5/X4/GT"
  VAL_LR_IMAGES_DIR: "/home/dl/Datasets/Set5/X4/LR"

MODEL:
  G:
    TYPE: "rrdbnet_x4"
    IN_CHANNELS: 3
    OUT_CHANNELS: 3
    CHANNELS: 64
    GROWTH_CHANNELS: 32
    NUM_RRDB: 23

TRAIN:
  RESUME_G: ""

  # train weights
  G_WEIGHTS_PATH: ""

  # train datasets
  IMAGE_SIZE: 256
  BATCH_SIZE: 16
  NUM_WORKERS: 4

  # train solver
  SOLVER:
    G:
      OPTIM: "Adam"
      LR: 0.0002
      BETAS: [ 0.9, 0.99 ]
      EPS: 0.0001 # Ensure mixed precision training does not appear Nan
      WEIGHT_DECAY: 0.0

      LR_SCHEDULER:
        TYPE: "StepLR"
        STEP_SIZE: 200  # epochs / 5
        GAMMA: 0.5

  # loss config
  LOSS:
    PIXEL:
      TYPE: "l1"
      WEIGHT: [ 1.0 ]

  # train hyper-parameters
  EPOCHS: 1000

  # train setup
  LOCAL_RANK: -1
  RANK: -1
  WORLD_SIZE: 1
  DIST_URL: "env://"

  # train results
  OUTPUT_DIR: "results/train"
  VERBOSE: True

EVAL:
  WEIGHTS_PATH: "realesrnet_x4-dfo2k.pkl"
  NIQE_WEIGHTS_PATH: "results/pretrained_models/niqe_model.mat"
  HALF: True
  ONLY_TEST_Y_CHANNEL: True